name: Web Sitesini Yayinla

on:
  push:
    branches: ["main"] # Eğer master kullanıyorsanız "master" yapın
  workflow_dispatch:

# 🌟 Depoya yazma yetkisi YOKTUR. Sadece Pages yayını için gereken standart izinler:
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Pages Ayarlarını Yapılandır
        uses: actions/configure-pages@v5

      - name: Dosya Listesini Geçici Olarak Oluştur
        run: |
          find . -type f ! -path '*/.*' ! -name 'index.html' | sed 's|^\./||' | jq -R . | jq -s . > dosyalar.json

      - name: Dosyaları Pakete Yükle
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: GitHub Pages OlaraK Yayinla
        id: deployment
        uses: actions/deploy-pages@v4
